# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:59
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_account', models.CharField(default='Nom du compte en banque', max_length=256, verbose_name='Nom du compte')),
                ('num_of_account', models.CharField(default='Identifiant', max_length=256, verbose_name='Identifiant du compte')),
            ],
            options={
                'ordering': ['name_of_account'],
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_bank', models.CharField(default='Nom de la banque', max_length=256, verbose_name='Nom de la banque')),
                ('num_of_bank', models.CharField(default='Identifiant', max_length=256, verbose_name='Identifiant de la banque')),
            ],
            options={
                'verbose_name_plural': 'banks',
                'verbose_name': 'bank',
                'ordering': ['name_of_bank'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transaction', models.DateField(default=datetime.datetime.now, verbose_name='Date de la transaction')),
                ('type_of_transaction', models.CharField(max_length=64, verbose_name='Type de transaction')),
                ('name_of_transaction', models.CharField(max_length=256, verbose_name='Fournisseur')),
                ('amount_of_transaction', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Montant de la transaction ')),
                ('currency_of_transaction', models.CharField(max_length=3, verbose_name='Devise')),
                ('creation_date', models.DateField(default=datetime.datetime.now, verbose_name='Date de saisie')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banksandaccounts.Accounts')),
            ],
            options={
                'ordering': ['date_of_transaction'],
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banksandaccounts.Banks'),
        ),
    ]
