# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksandaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['name_of_account'], 'verbose_name': 'compte banquaire', 'verbose_name_plural': 'comptes bancaires'},
        ),
        migrations.AlterModelOptions(
            name='banks',
            options={'ordering': ['name_of_bank'], 'verbose_name': 'banque', 'verbose_name_plural': 'banques'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['date_of_transaction'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
